import asyncio
from playwright.async_api import async_playwright
from _env import *
async def main():
  async with async_playwright() as p:
    b=await p.chromium.launch(executable_path=CHROME,args=['--autoplay-policy=no-user-gesture-required','--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream'])
    pg=await b.new_page(viewport={'width':1400,'height':900})
    errs=[]; pg.on('pageerror',lambda e: errs.append(str(e))); pg.on('console',lambda m: m.type=='error' and errs.append(m.text))
    await pg.add_init_script("try{localStorage.setItem('annotated-welcome-seen','1')}catch(e){}"); await pg.goto(PREVIEW)
    await pg.wait_for_selector('#videoMode:not([hidden]) .vTitle')
    V='#videoMode '; A='#articleMode '
    await pg.evaluate('document.getElementById("vid").currentTime=40'); await asyncio.sleep(.8); await pg.click(V+'.setStart')
    await pg.evaluate('document.getElementById("vid").currentTime=45'); await asyncio.sleep(.8); await pg.click(V+'.setEnd')
    await asyncio.sleep(.5)
    await pg.click(V+'.capBtn')
    await pg.wait_for_selector(V+'.vCompose:not([hidden])',timeout=30000)
    print('status:', await pg.inner_text(V+'.status'), '| capBtn class:', await pg.get_attribute(V+'.capBtn','class'))
    await pg.fill(V+'.takeInput','Video take')
    # article
    await pg.click('.tab >> nth=1'); await asyncio.sleep(.5)
    print('idle grab hidden:', not await pg.is_visible(A+'.grab'))
    await pg.evaluate("document.getElementById('pane').scrollTop=300"); await asyncio.sleep(.2)
    await pg.evaluate('''(()=>{const p=[...document.querySelectorAll(".story p")].find(x=>x.textContent.startsWith("Transit officials")).firstChild;const r=document.createRange();r.setStart(p,0);r.setEnd(p,p.nodeValue.indexOf("publish")+7);getSelection().removeAllRanges();getSelection().addRange(r)})()''')
    await asyncio.sleep(.5)
    print('quote:', await pg.inner_text(A+'.selQuote'))
    print('mode:', await pg.inner_text(A+'.selMode'))
    pos=await pg.evaluate("(()=>{const h=[...document.querySelectorAll('.annotated-ui')].find(h=>h.style.display==='block');const b=h.getBoundingClientRect();const s=document.querySelector('.story p').getBoundingClientRect();return [b.right, s.left]})()")
    print('button right edge, text left edge:', pos)
    await pg.click(A+'.exactBtn'); await asyncio.sleep(.4)
    print('exact quote:', await pg.inner_text(A+'.selQuote'), '| mode:', await pg.inner_text(A+'.selMode'))
    await pg.click(A+'.exactBtn'); await asyncio.sleep(.4)
    print('re-expanded:', (await pg.inner_text(A+'.selQuote'))[-40:])
    await pg.click(A+'.grab')
    await pg.wait_for_selector(A+'.aCompose:not([hidden])',timeout=15000)
    print('captured:', await pg.inner_text(A+'.capQuote'))
    await pg.click(A+'.ctxthumb'); await asyncio.sleep(.3); print('lightbox open:', await pg.is_visible('#annotated-shot')); await pg.click('#annotated-shot .strong')
    await pg.click(A+'.tagbtn >> text=Receipts'); await pg.fill(A+'.takeInput','Ridership numbers every month')
    await pg.click(A+'.publish')
    await pg.wait_for_selector('.annpage:not([hidden]) .ann:not(.loading)',timeout=10000)
    art_tab = await pg.inner_text('#urlbar')
    print('side panel:', (await pg.inner_text('#annMode'))[:120].replace('\n',' | '))
    # publish the video
    await pg.click('.tab >> nth=0'); await asyncio.sleep(.4)
    await pg.click(V+'.publish')
    await pg.wait_for_selector('.annpage:not([hidden]) .ann:not(.loading)',timeout=10000)
    print('video page stats:', await pg.inner_text('.annpage:not([hidden]) .stats'))
    print('video source card:', await pg.inner_text('.annpage:not([hidden]) .srcbar .sbWho'))
    # article page count updated?
    await pg.click('.tab >> nth=4'); await asyncio.sleep(.3)
    print('article page stats now:', await pg.inner_text('.annpage:not([hidden]) .stats'))
    # View page from the article panel must open the article annotation
    await pg.click('.tab >> nth=1'); await asyncio.sleep(.3)
    print('article scroll restored:', await pg.evaluate("document.getElementById('pane').scrollTop"))
    await pg.click(A+'.aPublished .view'); await asyncio.sleep(.3)
    print('article View page ->', await pg.inner_text('#urlbar'), '| expected', art_tab)
    # banner dismiss, comment shortcut, tag link, profile link
    print('banner gone on revisit:', await pg.locator('.annpage:not([hidden]) .banner').count()==0)
    await pg.fill('.annpage:not([hidden]) .cText','Shortcut comment'); await pg.press('.annpage:not([hidden]) .cText','Control+Enter')
    print('comments title:', await pg.inner_text('.annpage:not([hidden]) .cTitle'))
    await pg.click('.annpage:not([hidden]) .tagLink'); await asyncio.sleep(.3)
    print('tag feed:', (await pg.inner_text('.annpage:not([hidden])'))[:160].replace('\n',' | '))
    await pg.screenshot(path='r3_tagfeed.png')
    await pg.click('.annpage:not([hidden]) .allLink'); await asyncio.sleep(.3)
    print('profile:', (await pg.inner_text('.annpage:not([hidden]) .feedHead'))[:120].replace('\n',' | '))
    await pg.screenshot(path='r3_profile.png')
    await pg.click('.annpage:not([hidden]) .card >> nth=0'); await asyncio.sleep(.3)
    print('card opens:', await pg.inner_text('#urlbar'))
    await pg.screenshot(path='r3_ann.png')
    print('errors:', errs)
    await b.close()
asyncio.run(main())
